"""Public API for the first controlled local-write vertical slice."""

from .apply import apply_changeset
from .capability import (
    capability_fingerprint,
    normalize_repo_path,
    path_is_allowed,
    reconcile_write_capability,
    stable_path_union,
)
from .errors import (
    ChangePathError,
    ChangeProviderBlockedError,
    ChangeSetError,
    CheckpointBindingError,
    CheckpointError,
    CommitVerificationError,
    DeliveryReviewContextError,
    DeliveryReviewEvidenceError,
    DeliveryReviewProviderRequiredError,
    DeliveryReviewStateMismatchError,
    DeliveryReviewStorageError,
    ItemEvidenceError,
    ItemInputsMismatchError,
    MultiItemEvidenceError,
    MultiItemLineageError,
    PostCommitRecoveryRequired,
    ProviderMutationError,
    RepairFailureContextError,
    RepairLineageError,
    RepairPolicyError,
    RepairWorkspaceLineageError,
    ReviewProviderRequiredError,
    SemanticReviewBlockedError,
    SemanticReviewContextError,
    SemanticReviewEvidenceError,
    StaleFileError,
    UnsupportedWriteScopeError,
    ValidationExecutionError,
    WorkCapabilityMismatchError,
    WorkItemPolicyError,
    WorkPlanMismatchError,
    WorkspaceError,
    WorkspaceManifestError,
    WriteBaselineDriftError,
    WritePreparationError,
    WriteSliceError,
)
from .models import (
    AppliedChangeSet,
    AppliedFile,
    ChangeIntent,
    ChangeRequest,
    ChangeSet,
    CheckpointView,
    CommitWitness,
    CompletedItemReport,
    DeliveryCompletedItem,
    DeliveryManifest,
    DeliveryManifestEntry,
    DeliveryReviewContext,
    DeliveryReviewReport,
    FileChange,
    RepairFailureContext,
    RepairValidationDiagnostic,
    RepairValidationDiagnosticKind,
    SemanticReviewContext,
    WorkPlan,
    WorkPlanItem,
    WorkspaceManifest,
    WorkspaceManifestEntry,
    WriteInputs,
    WriteRunInputs,
    WriteSliceIssue,
    WriteSliceOutcome,
    WriteSliceReport,
    WriteSliceRequest,
    write_run_inputs_digest,
)
from .provider import ChangeProvider, ChangeProviderContext

__all__ = [
    "AppliedChangeSet",
    "AppliedFile",
    "ChangeIntent",
    "ChangePathError",
    "ChangeProvider",
    "ChangeProviderBlockedError",
    "ChangeProviderContext",
    "ChangeRequest",
    "ChangeSet",
    "ChangeSetError",
    "CheckpointBindingError",
    "CheckpointError",
    "CheckpointView",
    "CommitVerificationError",
    "CommitWitness",
    "CompletedItemReport",
    "DeliveryCompletedItem",
    "DeliveryManifest",
    "DeliveryManifestEntry",
    "DeliveryReviewContext",
    "DeliveryReviewContextError",
    "DeliveryReviewEvidenceError",
    "DeliveryReviewProviderRequiredError",
    "DeliveryReviewReport",
    "DeliveryReviewStateMismatchError",
    "DeliveryReviewStorageError",
    "FileChange",
    "ItemEvidenceError",
    "ItemInputsMismatchError",
    "MultiItemEvidenceError",
    "MultiItemLineageError",
    "PostCommitRecoveryRequired",
    "ProviderMutationError",
    "RepairFailureContext",
    "RepairFailureContextError",
    "RepairLineageError",
    "RepairPolicyError",
    "RepairValidationDiagnostic",
    "RepairValidationDiagnosticKind",
    "RepairWorkspaceLineageError",
    "ReviewProviderRequiredError",
    "SemanticReviewBlockedError",
    "SemanticReviewContext",
    "SemanticReviewContextError",
    "SemanticReviewEvidenceError",
    "StaleFileError",
    "UnsupportedWriteScopeError",
    "ValidationExecutionError",
    "WorkCapabilityMismatchError",
    "WorkItemPolicyError",
    "WorkPlan",
    "WorkPlanItem",
    "WorkPlanMismatchError",
    "WorkspaceError",
    "WorkspaceManifest",
    "WorkspaceManifestEntry",
    "WorkspaceManifestError",
    "WriteBaselineDriftError",
    "WriteInputs",
    "WritePreparationError",
    "WriteRunInputs",
    "WriteSliceError",
    "WriteSliceIssue",
    "WriteSliceOutcome",
    "WriteSliceReport",
    "WriteSliceRequest",
    "WriteSliceRunner",
    "apply_changeset",
    "capability_fingerprint",
    "normalize_repo_path",
    "path_is_allowed",
    "reconcile_write_capability",
    "stable_path_union",
    "write_run_inputs_digest",
]


def __getattr__(name: str):
    """Load the orchestrator lazily so node contracts do not form an import cycle."""

    if name == "WriteSliceRunner":
        from .runner import WriteSliceRunner

        return WriteSliceRunner
    raise AttributeError(name)
