"""Adapter-neutral immutable work-source contracts."""

from .commands import parse_validation_checks
from .errors import (
    InvalidWorkSourceError,
    WorkItemNotFoundError,
    WorkScopeNotFoundError,
    WorkSourceConfigurationError,
    WorkSourceError,
    WorkSourceFormatError,
    WorkSourcePathError,
)
from .models import (
    IssueSeverity,
    RepoPathSpec,
    ScopeSelection,
    SelectionKind,
    SourceDocumentRevision,
    SourceLocation,
    SourcePolicyHints,
    ValidationCheck,
    ValidationOrigin,
    WorkItem,
    WorkItemStatus,
    WorkPackage,
    WorkRisk,
    WorkScope,
    WorkScopeStatus,
    WorkSelection,
    WorkSourceIssue,
    WorkSourceRevision,
    WorkSourceSnapshot,
    WorkSourceValidation,
)
from .source import WorkSource

__all__ = [
    "InvalidWorkSourceError",
    "IssueSeverity",
    "RepoPathSpec",
    "ScopeSelection",
    "SelectionKind",
    "SourceDocumentRevision",
    "SourceLocation",
    "SourcePolicyHints",
    "ValidationCheck",
    "ValidationOrigin",
    "WorkItem",
    "WorkItemNotFoundError",
    "WorkItemStatus",
    "WorkPackage",
    "WorkRisk",
    "WorkScope",
    "WorkScopeNotFoundError",
    "WorkScopeStatus",
    "WorkSelection",
    "WorkSource",
    "WorkSourceConfigurationError",
    "WorkSourceError",
    "WorkSourceFormatError",
    "WorkSourceIssue",
    "WorkSourcePathError",
    "WorkSourceRevision",
    "WorkSourceSnapshot",
    "WorkSourceValidation",
    "parse_validation_checks",
]
